name: Run Black on PR
inputs:
    access-token:
      description: "GitHub access token"
      required: true
    path:
      description: "Directory to run Black on"
      required: true
      default: .
  line-length:
    description: "Black line length."
    required: false
    default: 88
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access-token }}
    - ${{ inputs.path }}
    - ${{ inputs.line-length }}

